apiVersion: v1
kind: Service
metadata:
  name: web-dacm-front
  namespace: nj-devenv-web
  labels:
    name: web-dacm-front
spec: 
  type: NodePort
  selector:
    name: web-dacm-front
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30830
    name: tcpport
